# Generated by Django 2.0.2 on 2018-03-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0002_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
